Drivetrain ready to add
SargonRobotics/Steamworks-2017 pull request #1
Opened 2017-01-11 23:52 UTC by awurst

Added commands for drive train. Added drive train subsystem. Added crucial methods for deadzone and getting the axis.

Should be good to go.

2017-01-12 02:49 UTC, SargonRobotics commented
You won't be here to confirm the final merge so I'm going to let someone else add the request.

2017-01-12 15:00 UTC, Ubspy commented
We were not aware that you could only issue one pull request. So this one is open again.

2017-01-12 17:52 UTC, Ubspy requested changes
Functionally this looks good, only in the Trigger file is there any optimization issues. But I'm requesting changes for spacing and neat code. Because you guys need good practice and I also have a really bad case of code OCD.

2017-01-12 17:52 UTC, Ubspy commented on src/org/usfirst/frc/team2335/robot/OI.java
> +
Your comments should be capitalized here. Just for readability, not that important. But always good practice.

2017-01-12 17:52 UTC, Ubspy commented on src/org/usfirst/frc/team2335/robot/Robot.java
> +
Add a TODO: comment saying we need to change the axes to be correct

2017-01-12 17:52 UTC, Ubspy commented on src/org/usfirst/frc/team2335/robot/commands/Drive.java
> + */
Remove this blank comment. Again it's just for neat code.

2017-01-12 17:52 UTC, Ubspy commented on src/org/usfirst/frc/team2335/robot/commands/Strafe.java
> +}
So this file has a lot of readability issues. First, the spacing, second the comments.

Any comments you want to keep or change? If you have none then you should remove all or them.

2017-01-12 17:52 UTC, Ubspy commented on src/org/usfirst/frc/team2335/robot/commands/Turn.java
> +}
Same thing for this file as the Strafe command, any comments you want to keep. If not the spacing and comments need to be fixed.

2017-01-12 17:52 UTC, Ubspy commented on src/org/usfirst/frc/team2335/robot/triggers/Axis.java
> +
There's no reason to use these constants. They're never referenced in any other file. Correct me if I'm wrong though.

2017-01-12 17:52 UTC, Ubspy commented on src/org/usfirst/frc/team2335/robot/triggers/Axis.java
> +    public boolean get()
Do we need to keep this comment?

2017-01-14 16:12 UTC, Ubspy commented on src/org/usfirst/frc/team2335/robot/OI.java
> +
So this issue is fixed, for some reason there are 2 commits that did the same thing.

2017-01-14 16:19 UTC, bobfor commented on src/org/usfirst/frc/team2335/robot/triggers/Axis.java
> +    public boolean get()
i don't think we do

2017-01-14 16:20 UTC, Ubspy commented on src/org/usfirst/frc/team2335/robot/triggers/Axis.java
> +    public boolean get()
For now let's keep it.

2017-01-14 16:27 UTC, Ubspy commented on src/org/usfirst/frc/team2335/robot/commands/Drive.java
> +}
This file has the same issues as the other ones, pls fix.

2017-01-14 16:50 UTC, Ubspy approved these changes

2017-01-14 16:52 UTC, merged