Vision branch is ready to merge with current features
SargonRobotics/Steamworks-2017 pull request #4
Opened 2017-02-03 14:01 UTC by Ubspy

Our current pipeline and functionality is "ready" to be added to the master branch for functionality on the rest of the branches. Ready is in quotes because this branch was entirely done by me, so I'll need you guys to look over it.

2017-02-03 17:08 UTC, bobfor commented on src/org/usfirst/frc/team2335/robot/Robot.java
> +					//TODO: Remove any irrelevant comments out of the cluster fuck below
Remove parts of this massive comment to make it look better and easier to understand

2017-02-03 17:09 UTC, bobfor commented on src/org/usfirst/frc/team2335/robot/subsystems/Vision.java
> +}
Add an extra line here

2017-02-03 17:13 UTC, bobfor commented on src/org/usfirst/frc/team2335/robot/Robot.java
> +/**
remove this comment

2017-02-03 17:24 UTC, bobfor commented on src/org/usfirst/frc/team2335/robot/OI.java
> +//TODO: Rename to OperatorInterface after basic functionality for clarity.
When are we going to go through and fix all the stuff that the TODO comments tell us to fix

2017-02-03 17:24 UTC, bobfor reviewed
The code looked pretty good. Documentation needs improvement to make sure there are no useless comments or confusing comments that make it hard to understand what's going on.

2017-02-04 15:31 UTC, PancakeUniverse commented on src/org/usfirst/frc/team2335/robot/Robot.java
> +
Comment-a-saurus rex needs to die

2017-02-04 15:34 UTC, PancakeUniverse commented on src/org/usfirst/frc/team2335/robot/subsystems/DriveTrain.java
> +
what does this do?

2017-02-04 15:34 UTC, PancakeUniverse commented on src/org/usfirst/frc/team2335/robot/subsystems/DriveTrain.java
> +
(that line you added)

2017-02-04 15:35 UTC, BenjumanjiBrah commented on src/org/usfirst/frc/team2335/robot/Robot.java
>  		if (autonomousCommand != null)
Don't you need a semi-colon after if (autonomousCommand != null)

2017-02-04 15:43 UTC, awurst commented on src/org/usfirst/frc/team2335/robot/commands/CenterRobot.java
> +    	DriverStation.reportWarning("Centered", true);
How does this display in the Driver Station? Like what line and how is that coded?

2017-02-04 15:44 UTC, PancakeUniverse requested changes
Has some large comments, especially the unholy monstrosity in the middle of the program, this needs to be removed or shrunk. The program itself seems fine, and should work well enough.

2017-02-04 15:44 UTC, BenjumanjiBrah commented on src/org/usfirst/frc/team2335/robot/Robot.java
> +		//Please for the love of god don't forget this line or else nothing works and I lose will to live
No depression allowed in programming

2017-02-04 15:46 UTC, awurst commented on src/org/usfirst/frc/team2335/robot/GripPipeline.java
> +public class GripPipeline implements VisionPipeline {
What is the GripPipeline class? Also VisionPipeline and other pipeline things used later.

2017-02-04 15:49 UTC, BenjumanjiBrah commented on src/org/usfirst/frc/team2335/robot/OI.java
> -		amount = (Math.abs(amount) <= Robot.DEADZONE ? 0 : (amount = (amount < 0) ? amount : amount));
please explain the math.abs stuff its kind of confusing

2017-02-04 15:50 UTC, awurst commented on src/org/usfirst/frc/team2335/robot/GripPipeline.java
> +		double[] hslThresholdLuminance = {169.69424460431657, 252.83531409168083};
What values are these massive decimals?

2017-02-04 15:53 UTC, awurst approved these changes
It all seems functional, I don't understand all of the math, but I get most of it.

2017-02-04 20:15 UTC, Ubspy commented on src/org/usfirst/frc/team2335/robot/GripPipeline.java
> +		double[] hslThresholdLuminance = {169.69424460431657, 252.83531409168083};
This is an auto generated file from GRIP, so that's what GRIP felt like using

2017-02-04 20:16 UTC, Ubspy commented on src/org/usfirst/frc/team2335/robot/OI.java
> +//TODO: Rename to OperatorInterface after basic functionality for clarity.
Right now some of these TODOs aren't too important, and just need to be fixed eventually.

2017-02-04 20:16 UTC, Ubspy commented on src/org/usfirst/frc/team2335/robot/OI.java
> -		amount = (Math.abs(amount) <= Robot.DEADZONE ? 0 : (amount = (amount < 0) ? amount : amount));
Math.abs gets the absolute value of the inputed number

2017-02-04 20:17 UTC, Ubspy commented on src/org/usfirst/frc/team2335/robot/Robot.java
> +/**
Why remove it?

2017-02-04 20:19 UTC, Ubspy commented on src/org/usfirst/frc/team2335/robot/commands/CenterRobot.java
> +    	DriverStation.reportWarning("Centered", true);
It's in the bottom right box, it'll output a warning message.

2017-02-04 20:28 UTC, bobfor commented on src/org/usfirst/frc/team2335/robot/Robot.java
> +/**
It's unimportant and distracting

2017-02-04 20:31 UTC, PancakeUniverse approved these changes
Giant comment removed, mission accomplished. Rest of the program seems functional and working.

2017-02-09 17:00 UTC, merged